import Head from "next/head";
import FeaturedBooks from "@/components/home-page/featured-books";
import LandingComponent from "@/components/home-page/landing-component";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LandingComponent></LandingComponent>
      <FeaturedBooks></FeaturedBooks>
    </>
  );
}
